class GestoreCalcoli:
	def add(self,numero1,numero2):
		return numero1+numero2
	def sub(self,numero1,numero2):
		return numero1-numero2
	def mul(self,numero1,numero2):
		return numero1*numero2
	def div(self,numero1,numero2):
		return numero1/numero2